### PR TITLE
fix(blog): missing gap between sidebar menu items

### LINKED ISSUE #255: fix(ui-components): missing gap between side-panel-menu items
The gap between `ui-side-panel-menu-item` elements is missing in all sidebars. Pre-existing issue — present on `main` before the Lit migration (#254).

The `.menu` container has `gap: var(--ui-spm-item-gap, SP_0_5)` but it may not be applying. Investigate whether the gap CSS is reaching the rendered DOM.

### PR DESCRIPTION
**Pull request by kiennt23**
## Summary
- Restore `.menu { gap }` + `::slotted(div)` gap in `ui-side-panel-menu`
- Remove wrapper `<div data-slug>` around sidebar items in blog editor
- Add `display: contents` on `#admin-post-list` / `#admin-project-list` divs so items participate in flex gap
- Add `willUpdate()` for property cascades in `ui-side-panel-menu` (mobile → state)
- Move `attributeChangedCallback` logic to `updated()` in `ui-side-panel-menu`
- Fix `declare` + constructor defaults for `ui-side-panel-menu-section` separator property

## Why
Blog editor items were wrapped in `<div data-slug>` inside `<div id="admin-post-list">` inside `<editor-sidebar display:contents>` — three levels deep from the slot. The `.menu { gap }` only applies between direct flex children. Removing the wrapper divs and using `display: contents` on the list containers makes items direct flex participants.

Closes #255

### CODE REVIEW

File: packages/ui-components/src/components/ui-side-panel-menu-section.ts [hunk 1]
```diff
@@ -54,6 +59,11 @@ export class UiSidePanelMenuSection extends LitElement {
     }
   `;
 
+  // Synchronous first render for imperative consumers + happy-dom tests
+  protected override scheduleUpdate(): void | Promise<unknown> {
+    this.performUpdate();
+  }
+
```
Comment (kiennt23) [inline packages/ui-components/src/components/ui-side-panel-menu-section.ts]: do we really need this?
